### PR TITLE
pkg/ledger: fix transaction signing

### LINKED ISSUE #297: ledger transfer will result with error: signature has wrong length
**Describe the bug**
doing a transfer via cli and ledger will result with the error 
```
error: signature has wrong length
```
tested with v1.2.4, v1.2.6, v1.2.9 most recent one has been tested by a community user and they hit the same issue 

**To Reproduce**
```
./hmy --node=https://api.s0.t.hmny.io transfer     --from one1xxxxxxxxxxxxxxxxxxx --to one1xxxxxxxxxxxxxxxxxxx --from-shard 0 --to-shard 1 --amount 0.000001 --ledger
2023/03/22 10:16:34 Couldn't sign transaction, error: signature has wrong length
```

**Expected behavior**
> A clear and concise description of what you expected to happen.

signature prompt on ledger should appear. in this case, nothing happen, the error just happen directly.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

NA

**Environment (please complete the following information):**
 - OS: Linux ubuntu 20
- hmy ledger app 1.6.0
- hmy cli most recent and v1.2.4, v1.2.6, v1.2.9

**Additional context**

### PR DESCRIPTION
**Pull request by MaxMustermann2**
Split the message to be signed into packets of size 255. The implementation is simply copied over from staking transaction signing.

Closes #297

See also harmony-one/staking-dashboard#637

### CODE REVIEW

File: pkg/ledger/nano_S_driver.go [hunk 1]
```diff
@@ -208,12 +208,21 @@ func (n *NanoS) GetAddress() (oneAddr string, err error) {
 }
 
 func (n *NanoS) SignTxn(txn []byte) (sig [signatureSize]byte, err error) {
+	bug := bytes.NewBuffer(txn)
```
Comment (sophoah) [inline pkg/ledger/nano_S_driver.go:211]: typo here should be buf

**Review by sophoah — CHANGES_REQUESTED** [review]
